// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/proto/metrics/v1/metrics.proto

package metricsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Мы передаём тот же формат, что и по HTTP: gzip JSON (а при наличии RSA — зашифрованный gzip JSON).
type PushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тело сообщения: либо gzip(JSON{Metric}), либо RSA( gzip(JSON{Metric}) ), если encrypted=true.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// HMAC-SHA256 (hex) от payload, если KEY задан. Совпадает с логикой HTTP (хэш от фактических байтов тела).
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Аналог X-Real-IP, чтобы сервер мог проверить TRUSTED_SUBNET (если не указано, сервер попробует peer addr).
	AgentIp string `protobuf:"bytes,3,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	// true — если payload зашифрован RSA.
	Encrypted     bool `protobuf:"varint,4,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_internal_proto_metrics_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PushRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PushRequest) GetAgentIp() string {
	if x != nil {
		return x.AgentIp
	}
	return ""
}

func (x *PushRequest) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

type PushResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Failed        int64                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_internal_proto_metrics_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *PushResult) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PushResult) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

var File_internal_proto_metrics_v1_metrics_proto protoreflect.FileDescriptor

const file_internal_proto_metrics_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"'internal/proto/metrics/v1/metrics.proto\x12\n" +
	"metrics.v1\"t\n" +
	"\vPushRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x19\n" +
	"\bagent_ip\x18\x03 \x01(\tR\aagentIp\x12\x1c\n" +
	"\tencrypted\x18\x04 \x01(\bR\tencrypted\"@\n" +
	"\n" +
	"PushResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x03R\x06failed2K\n" +
	"\x0eMetricsService\x129\n" +
	"\x04Push\x12\x17.metrics.v1.PushRequest\x1a\x16.metrics.v1.PushResult(\x01BOZMgithub.com/antonminaichev/metricscollector/internal/proto/metricsv1;metricsv1b\x06proto3"

var (
	file_internal_proto_metrics_v1_metrics_proto_rawDescOnce sync.Once
	file_internal_proto_metrics_v1_metrics_proto_rawDescData []byte
)

func file_internal_proto_metrics_v1_metrics_proto_rawDescGZIP() []byte {
	file_internal_proto_metrics_v1_metrics_proto_rawDescOnce.Do(func() {
		file_internal_proto_metrics_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_v1_metrics_proto_rawDesc), len(file_internal_proto_metrics_v1_metrics_proto_rawDesc)))
	})
	return file_internal_proto_metrics_v1_metrics_proto_rawDescData
}

var file_internal_proto_metrics_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_metrics_v1_metrics_proto_goTypes = []any{
	(*PushRequest)(nil), // 0: metrics.v1.PushRequest
	(*PushResult)(nil),  // 1: metrics.v1.PushResult
}
var file_internal_proto_metrics_v1_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.v1.MetricsService.Push:input_type -> metrics.v1.PushRequest
	1, // 1: metrics.v1.MetricsService.Push:output_type -> metrics.v1.PushResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_metrics_v1_metrics_proto_init() }
func file_internal_proto_metrics_v1_metrics_proto_init() {
	if File_internal_proto_metrics_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_v1_metrics_proto_rawDesc), len(file_internal_proto_metrics_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_metrics_v1_metrics_proto_goTypes,
		DependencyIndexes: file_internal_proto_metrics_v1_metrics_proto_depIdxs,
		MessageInfos:      file_internal_proto_metrics_v1_metrics_proto_msgTypes,
	}.Build()
	File_internal_proto_metrics_v1_metrics_proto = out.File
	file_internal_proto_metrics_v1_metrics_proto_goTypes = nil
	file_internal_proto_metrics_v1_metrics_proto_depIdxs = nil
}
